---
apiVersion: v1
kind: Pod
metadata:
  labels:
    app: mypod
  name: mypod-node-selc
spec:
  containers:
  - image: httpd:latest
    name: con1
    ports:
    - containerPort: 80
  nodeSelector:
     cpu: ryzen

      
     
