apiVersion: v1
kind: Service
metadata:
  name: mypod-svc
spec:
  type: NodePort
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
    nodePort: 30123
  selector:
    app: mypod
---
---
apiVersion: v1
kind: Pod
metadata:
  annotations:
     enableistio: "true"
  labels:
    app: mypod
    env: dev
  name: mypod
spec:
  containers:
  - image: httpd:latest
    name: con1
    ports:
    - containerPort: 80
  - image: tomcat:latest
    name: con2
    ports:
    - containerPort: 8080
    resources:
       requests:
         memory: "64Mi"
         cpu: "250m"
       limits:
         memory: "128Mi"
         cpu: "500m"
    
